package Assignment2;

/**
* Assignment2/FileShareServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./server.idl
* Saturday, January 25, 2025 5:51:19 o'clock PM MST
*/

public final class FileShareServerHolder implements org.omg.CORBA.portable.Streamable
{
  public Assignment2.FileShareServer value = null;

  public FileShareServerHolder ()
  {
  }

  public FileShareServerHolder (Assignment2.FileShareServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Assignment2.FileShareServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Assignment2.FileShareServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Assignment2.FileShareServerHelper.type ();
  }

}
