package Assignment2;


/**
* Assignment2/FileShareServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Tuesday, January 7, 2025 9:49:31 o'clock PM MST
*/

abstract public class FileShareServerHelper
{
  private static String  _id = "IDL:Assignment2/FileShareServer:1.0";

  public static void insert (org.omg.CORBA.Any a, Assignment2.FileShareServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Assignment2.FileShareServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Assignment2.FileShareServerHelper.id (), "FileShareServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Assignment2.FileShareServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileShareServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Assignment2.FileShareServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Assignment2.FileShareServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Assignment2.FileShareServer)
      return (Assignment2.FileShareServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Assignment2._FileShareServerStub stub = new Assignment2._FileShareServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Assignment2.FileShareServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Assignment2.FileShareServer)
      return (Assignment2.FileShareServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Assignment2._FileShareServerStub stub = new Assignment2._FileShareServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
