package Assignment2;


/**
* Assignment2/FileShareServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Tuesday, January 7, 2025 9:49:31 o'clock PM MST
*/

public interface FileShareServerOperations 
{
  Assignment2.KeyVal[] getFiles ();
  boolean insertFile (String host, String filename);
  String getFile (String filename);
} // interface FileShareServerOperations
