package Assignment2;


/**
* Assignment2/FileShareServerPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Tuesday, January 7, 2025 9:49:31 o'clock PM MST
*/

public class FileShareServerPOATie extends FileShareServerPOA
{

  // Constructors

  public FileShareServerPOATie ( Assignment2.FileShareServerOperations delegate ) {
      this._impl = delegate;
  }
  public FileShareServerPOATie ( Assignment2.FileShareServerOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public Assignment2.FileShareServerOperations _delegate() {
      return this._impl;
  }
  public void _delegate (Assignment2.FileShareServerOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public Assignment2.KeyVal[] getFiles ()
  {
    return _impl.getFiles();
  } // getFiles

  public boolean insertFile (String host, String filename)
  {
    return _impl.insertFile(host, filename);
  } // insertFile

  public String getFile (String filename)
  {
    return _impl.getFile(filename);
  } // getFile

  private Assignment2.FileShareServerOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class FileShareServerPOATie
