package Assignment2;


/**
* Assignment2/KeyValSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Tuesday, January 7, 2025 9:49:31 o'clock PM MST
*/

public final class KeyValSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public Assignment2.KeyVal value[] = null;

  public KeyValSeqHolder ()
  {
  }

  public KeyValSeqHolder (Assignment2.KeyVal[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Assignment2.KeyValSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Assignment2.KeyValSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Assignment2.KeyValSeqHelper.type ();
  }

}
