package Assignment2;

/**
* Assignment2/KeyValHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Tuesday, January 7, 2025 9:49:31 o'clock PM MST
*/

public final class KeyValHolder implements org.omg.CORBA.portable.Streamable
{
  public Assignment2.KeyVal value = null;

  public KeyValHolder ()
  {
  }

  public KeyValHolder (Assignment2.KeyVal initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Assignment2.KeyValHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Assignment2.KeyValHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Assignment2.KeyValHelper.type ();
  }

}
