package Assignment2;


/**
* Assignment2/KeyVal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./server.idl
* Saturday, January 25, 2025 5:51:19 o'clock PM MST
*/

public final class KeyVal implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public String port = null;
  public String value = null;

  public KeyVal ()
  {
  } // ctor

  public KeyVal (String _key, String _port, String _value)
  {
    key = _key;
    port = _port;
    value = _value;
  } // ctor

} // class KeyVal
