package Assignment2;


/**
* Assignment2/KeyValHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./server.idl
* Saturday, January 25, 2025 5:51:19 o'clock PM MST
*/

abstract public class KeyValHelper
{
  private static String  _id = "IDL:Assignment2/KeyVal:1.0";

  public static void insert (org.omg.CORBA.Any a, Assignment2.KeyVal that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Assignment2.KeyVal extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "key",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "port",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "value",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Assignment2.KeyValHelper.id (), "KeyVal", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Assignment2.KeyVal read (org.omg.CORBA.portable.InputStream istream)
  {
    Assignment2.KeyVal value = new Assignment2.KeyVal ();
    value.key = istream.read_string ();
    value.port = istream.read_string ();
    value.value = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Assignment2.KeyVal value)
  {
    ostream.write_string (value.key);
    ostream.write_string (value.port);
    ostream.write_string (value.value);
  }

}
