package Assignment2;


/**
* Assignment2/KeyValSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Tuesday, January 7, 2025 9:49:31 o'clock PM MST
*/

abstract public class KeyValSeqHelper
{
  private static String  _id = "IDL:Assignment2/KeyValSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, Assignment2.KeyVal[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Assignment2.KeyVal[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Assignment2.KeyValHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Assignment2.KeyValSeqHelper.id (), "KeyValSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Assignment2.KeyVal[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Assignment2.KeyVal value[] = null;
    int _len0 = istream.read_long ();
    value = new Assignment2.KeyVal[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Assignment2.KeyValHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Assignment2.KeyVal[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Assignment2.KeyValHelper.write (ostream, value[_i0]);
  }

}
