package Assignment2;


/**
* Assignment2/KeyVal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Tuesday, January 7, 2025 9:49:31 o'clock PM MST
*/

public final class KeyVal implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public String value = null;

  public KeyVal ()
  {
  } // ctor

  public KeyVal (String _key, String _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class KeyVal
